import { Router } from "express";
import { accountsRouter } from "./accounts.js";
import { transfersRouter } from "./transfers.js";
import { transactionsRouter } from "./transactions.js";
import { authRouter } from "./auth.js";
import { beneficiariesRouter } from "./beneficiaries.js";
import { cardsRouter } from "./cards.js";
import { kycRouter } from "./kyc.js";
import { paymentsRouter } from "./payments.js";
import { banksRouter } from "./banks.js";
import { fxRouter } from "./fx.js";
import { budgetsRouter } from "./budgets.js";
import { savingsRouter } from "./savings.js";
import { notificationsRouter } from "./notifications.js";
import { analyticsRouter } from "./analytics.js";
import { adminRouter } from "./admin.js";

export const router = Router();
router.use("/accounts", accountsRouter);
router.use("/transfers", transfersRouter);
router.use("/transactions", transactionsRouter);
router.use("/auth", authRouter);
router.use("/beneficiaries", beneficiariesRouter);
router.use("/cards", cardsRouter);
router.use("/kyc", kycRouter);
router.use("/payments", paymentsRouter);
router.use("/banks", banksRouter);
router.use("/fx", fxRouter);
router.use("/budgets", budgetsRouter);
router.use("/savings", savingsRouter);
router.use("/notifications", notificationsRouter);
router.use("/analytics", analyticsRouter);
router.use("/admin", adminRouter);
